-- Phase 0B: nullable tenant columns (additive only)

ALTER TABLE fyh_admin_users ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_auth_sessions ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_settings ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_customers ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_customer_notes ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_customer_timeline ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_financial_ledger ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_staff ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_service_categories ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_services ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_service_staff ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_service_consumables ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_commission_rules ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_brands ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_products ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_vendors ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_vendor_notes ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_vendor_payables ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_vendor_payments ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_vendor_payment_allocations ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_membership_plans ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_customer_memberships ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_package_plans ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_customer_packages ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_bridal_profiles ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_bridal_events ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_notification_templates ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_notification_outbox ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_historical_import_batches ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_historical_import_row_errors ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE wf_engine_memberships ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE wf_permission_grants ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE wf_role_templates ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE wf_payroll_runs ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE wf_payroll_lines ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE wf_incentive_plans ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE wf_incentives ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE wf_audit_log ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE wf_events ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_staff_schedules ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_staff_schedules ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_resources ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_resources ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_appointments ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_appointments ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_appointment_services ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_appointment_services ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_invoices ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_invoices ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_invoice_lines ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_invoice_lines ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_invoice_payments ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_invoice_payments ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_credit_notes ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_credit_notes ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_invoice_line_attributions ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_invoice_line_attributions ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_commission_entries ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_commission_entries ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_stock_movements ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_stock_movements ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_stock_adjustments ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_stock_adjustments ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_floor_issues ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_floor_issues ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_product_batches ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_product_batches ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_purchase_orders ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_purchase_orders ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_purchase_order_lines ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_purchase_order_lines ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_goods_receipts ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_goods_receipts ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_goods_receipt_lines ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_goods_receipt_lines ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_purchases ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_purchases ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_purchase_lines ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_purchase_lines ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_purchase_returns ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_purchase_returns ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_purchase_return_lines ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_purchase_return_lines ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_purchase_audit_events ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_purchase_audit_events ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE fyh_expenses ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE fyh_expenses ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE wf_schedules ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE wf_schedules ADD COLUMN IF NOT EXISTS location_id uuid;
ALTER TABLE wf_attendance ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE wf_attendance ADD COLUMN IF NOT EXISTS location_id uuid;

-- Admin / workforce identity links
ALTER TABLE fyh_admin_users ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE wf_employees ADD COLUMN IF NOT EXISTS organization_id uuid;
ALTER TABLE wf_employees ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE wf_employees ADD COLUMN IF NOT EXISTS fyh_staff_id uuid REFERENCES fyh_staff (id) ON DELETE SET NULL;

-- Partial indexes for backfill verification
CREATE INDEX IF NOT EXISTS fyh_admin_users_organization_id_idx ON fyh_admin_users (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_auth_sessions_organization_id_idx ON fyh_auth_sessions (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_settings_organization_id_idx ON fyh_settings (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_customers_organization_id_idx ON fyh_customers (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_customer_notes_organization_id_idx ON fyh_customer_notes (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_customer_timeline_organization_id_idx ON fyh_customer_timeline (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_financial_ledger_organization_id_idx ON fyh_financial_ledger (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_staff_organization_id_idx ON fyh_staff (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_service_categories_organization_id_idx ON fyh_service_categories (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_services_organization_id_idx ON fyh_services (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_service_staff_organization_id_idx ON fyh_service_staff (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_service_consumables_organization_id_idx ON fyh_service_consumables (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_commission_rules_organization_id_idx ON fyh_commission_rules (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_brands_organization_id_idx ON fyh_brands (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_products_organization_id_idx ON fyh_products (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_vendors_organization_id_idx ON fyh_vendors (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_vendor_notes_organization_id_idx ON fyh_vendor_notes (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_vendor_payables_organization_id_idx ON fyh_vendor_payables (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_vendor_payments_organization_id_idx ON fyh_vendor_payments (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_vendor_payment_allocations_organization_id_idx ON fyh_vendor_payment_allocations (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_membership_plans_organization_id_idx ON fyh_membership_plans (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_customer_memberships_organization_id_idx ON fyh_customer_memberships (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_package_plans_organization_id_idx ON fyh_package_plans (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_customer_packages_organization_id_idx ON fyh_customer_packages (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_bridal_profiles_organization_id_idx ON fyh_bridal_profiles (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_bridal_events_organization_id_idx ON fyh_bridal_events (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_notification_templates_organization_id_idx ON fyh_notification_templates (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_notification_outbox_organization_id_idx ON fyh_notification_outbox (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_historical_import_batches_organization_id_idx ON fyh_historical_import_batches (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_historical_import_row_errors_organization_id_idx ON fyh_historical_import_row_errors (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS wf_engine_memberships_organization_id_idx ON wf_engine_memberships (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS wf_permission_grants_organization_id_idx ON wf_permission_grants (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS wf_role_templates_organization_id_idx ON wf_role_templates (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS wf_payroll_runs_organization_id_idx ON wf_payroll_runs (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS wf_payroll_lines_organization_id_idx ON wf_payroll_lines (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS wf_incentive_plans_organization_id_idx ON wf_incentive_plans (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS wf_incentives_organization_id_idx ON wf_incentives (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS wf_audit_log_organization_id_idx ON wf_audit_log (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS wf_events_organization_id_idx ON wf_events (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_staff_schedules_organization_id_idx ON fyh_staff_schedules (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_resources_organization_id_idx ON fyh_resources (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_appointments_organization_id_idx ON fyh_appointments (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_appointment_services_organization_id_idx ON fyh_appointment_services (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_invoices_organization_id_idx ON fyh_invoices (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_invoice_lines_organization_id_idx ON fyh_invoice_lines (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_invoice_payments_organization_id_idx ON fyh_invoice_payments (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_credit_notes_organization_id_idx ON fyh_credit_notes (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_invoice_line_attributions_organization_id_idx ON fyh_invoice_line_attributions (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_commission_entries_organization_id_idx ON fyh_commission_entries (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_stock_movements_organization_id_idx ON fyh_stock_movements (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_stock_adjustments_organization_id_idx ON fyh_stock_adjustments (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_floor_issues_organization_id_idx ON fyh_floor_issues (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_product_batches_organization_id_idx ON fyh_product_batches (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_purchase_orders_organization_id_idx ON fyh_purchase_orders (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_purchase_order_lines_organization_id_idx ON fyh_purchase_order_lines (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_goods_receipts_organization_id_idx ON fyh_goods_receipts (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_goods_receipt_lines_organization_id_idx ON fyh_goods_receipt_lines (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_purchases_organization_id_idx ON fyh_purchases (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_purchase_lines_organization_id_idx ON fyh_purchase_lines (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_purchase_returns_organization_id_idx ON fyh_purchase_returns (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_purchase_return_lines_organization_id_idx ON fyh_purchase_return_lines (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_purchase_audit_events_organization_id_idx ON fyh_purchase_audit_events (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_expenses_organization_id_idx ON fyh_expenses (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS wf_schedules_organization_id_idx ON wf_schedules (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS wf_attendance_organization_id_idx ON wf_attendance (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS wf_employees_organization_id_idx ON wf_employees (organization_id) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_staff_schedules_location_id_idx ON fyh_staff_schedules (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_resources_location_id_idx ON fyh_resources (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_appointments_location_id_idx ON fyh_appointments (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_appointment_services_location_id_idx ON fyh_appointment_services (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_invoices_location_id_idx ON fyh_invoices (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_invoice_lines_location_id_idx ON fyh_invoice_lines (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_invoice_payments_location_id_idx ON fyh_invoice_payments (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_credit_notes_location_id_idx ON fyh_credit_notes (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_invoice_line_attributions_location_id_idx ON fyh_invoice_line_attributions (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_commission_entries_location_id_idx ON fyh_commission_entries (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_stock_movements_location_id_idx ON fyh_stock_movements (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_stock_adjustments_location_id_idx ON fyh_stock_adjustments (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_floor_issues_location_id_idx ON fyh_floor_issues (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_product_batches_location_id_idx ON fyh_product_batches (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_purchase_orders_location_id_idx ON fyh_purchase_orders (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_purchase_order_lines_location_id_idx ON fyh_purchase_order_lines (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_goods_receipts_location_id_idx ON fyh_goods_receipts (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_goods_receipt_lines_location_id_idx ON fyh_goods_receipt_lines (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_purchases_location_id_idx ON fyh_purchases (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_purchase_lines_location_id_idx ON fyh_purchase_lines (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_purchase_returns_location_id_idx ON fyh_purchase_returns (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_purchase_return_lines_location_id_idx ON fyh_purchase_return_lines (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_purchase_audit_events_location_id_idx ON fyh_purchase_audit_events (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS fyh_expenses_location_id_idx ON fyh_expenses (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS wf_schedules_location_id_idx ON wf_schedules (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS wf_attendance_location_id_idx ON wf_attendance (location_id) WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS wf_employees_user_id_idx ON wf_employees (user_id) WHERE user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS wf_employees_fyh_staff_id_idx ON wf_employees (fyh_staff_id) WHERE fyh_staff_id IS NOT NULL;
