import { VACATING_NOTICE_MIN_DAYS } from '@/src/services/billing';
import type { GuideCatalog } from '@/src/lib/guides/types';

export const ADMIN_GUIDE: GuideCatalog = {
  id: 'admin',
  title: 'Admin & manager guide',
  subtitle:
    'Setup, daily operations, billing, and troubleshooting. Search any problem below to find steps.',
  articles: [
    // ── Getting started ──
    {
      id: 'admin-login-roles',
      title: 'Sign in, roles & permissions',
      category: 'Getting started',
      keywords: ['login', 'role', 'permission', 'manager', 'accountant', 'viewer', 'access'],
      summary: 'Each admin has a role that controls which actions they can perform.',
      bullets: [
        'super_admin — full access including system routes.',
        'pg_manager — manage assigned PGs, tenants, billing.',
        'accountant — collections, invoices, deposits.',
        'viewer — read-only where permitted.',
        'Sign in at /admin/login. Change password from account settings when prompted.',
      ],
      links: [{ label: 'Admin login', href: '/admin/login' }],
    },
    {
      id: 'admin-overview',
      title: 'Overview dashboard',
      category: 'Getting started',
      keywords: ['overview', 'dashboard', 'metrics', 'income', 'occupancy', 'month'],
      summary: 'Monthly snapshot of collections, occupancy, deposit refunds, and per-PG income.',
      steps: [
        'Open Overview from the sidebar.',
        'Pick billing month with the month picker.',
        'Review rent/electricity collected, extra income, deposit refunds, occupancy %.',
        'Use the donut chart and PG table for per-property breakdown.',
        'Quick links jump to PG listings, Collections, or Residents.',
      ],
      links: [{ label: 'Overview', href: '/admin' }],
    },

    // ── PG setup ──
    {
      id: 'create-pg',
      title: 'Create a new PG listing',
      category: 'PG setup',
      keywords: ['create', 'new pg', 'listing', 'property', 'slug'],
      summary: 'Add a property before rooms, beds, and collections can be configured.',
      steps: [
        'PG listings → Create new PG.',
        'Enter name, address, slug (URL), gender policy, amenities.',
        'Upload photos/videos. Set Active when ready to show on website.',
        'Continue to Rooms & electricity, then Collections setup.',
      ],
      links: [
        { label: 'PG listings', href: '/admin/pgs' },
        { label: 'Create PG', href: '/admin/pgs/new' },
      ],
    },
    {
      id: 'pg-listing-edit',
      title: 'Edit listing, photos & amenities',
      category: 'PG setup',
      keywords: ['listing', 'photos', 'amenities', 'edit', 'archive', 'active'],
      summary: 'Update marketing content customers see on the public PG page.',
      steps: [
        'PG listings → open PG → Listing tab.',
        'Edit details, amenities, media galleries.',
        'Toggle Active to hide/show on website.',
        'Archive PG only when permanently closing (irreversible for customers).',
      ],
    },
    {
      id: 'rooms-beds-pricing',
      title: 'Add rooms, beds & pricing',
      category: 'PG setup',
      keywords: ['room', 'bed', 'pricing', 'floor', 'sharing', 'ac', 'rate'],
      summary: 'Inventory lives under Rooms & electricity for each PG.',
      steps: [
        'Open PG → Rooms & electricity.',
        'Add floors/rooms with type, sharing count, AC flag.',
        'Add beds (B1, B2, …) per room.',
        'Set daily/weekly/monthly rent and security deposit per bed.',
        'Archive beds/rooms instead of deleting when retired.',
      ],
      links: [{ label: 'Example rooms page', href: '/admin/pgs' }],
    },
    {
      id: 'collections-qr-setup',
      title: 'Set up UPI QR & payment categories',
      category: 'PG setup',
      keywords: ['qr', 'upi', 'collections', 'payment category', 'rent', 'electricity'],
      summary: 'Each PG needs QR payments enabled before customers can pay online.',
      steps: [
        'Open PG → Collections tab.',
        'Enable QR payments and upload the PG UPI QR image.',
        'Create Rent and Electricity payment categories (used on pay pages).',
        'Test with a small booking payment in staging before go-live.',
      ],
    },

    // ── Bed map ──
    {
      id: 'bed-map-basics',
      title: 'Using the bed map',
      category: 'Bed map',
      keywords: ['bed map', 'floor', 'room', 'visual', 'status', 'legend'],
      summary: 'Movie-seat view of every bed — click for resident details and actions.',
      bullets: [
        'Green — open for booking. Grey — occupied. Purple — booked/reserved. Orange — notice. Blue — pre-book.',
        'Click a bed to open the side panel: resident, billing links, vacating, move bed.',
        'Summary strip shows total, occupied, open, reserved, vacating counts.',
      ],
      links: [{ label: 'PG listings → Bed map', href: '/admin/pgs' }],
    },
    {
      id: 'manual-occupied',
      title: 'Mark a bed occupied (without tenant)',
      category: 'Bed map',
      keywords: ['occupied', 'manual', 'hide', 'available', 'block booking'],
      summary: 'Hide an empty bed from the website without assigning someone.',
      steps: [
        'Bed map → click an open bed.',
        'Use Mark as occupied in the side panel.',
        'Bed shows grey on admin and customer maps; not bookable.',
        'Mark as open · book now when ready to list again.',
      ],
    },
    {
      id: 'assign-from-map',
      title: 'Assign or reserve tenant from bed map',
      category: 'Bed map',
      keywords: ['assign', 'reserve', 'tenant', 'open bed', 'move in'],
      summary: 'Open beds link directly to Assign tenant with bed pre-selected.',
      steps: [
        'Click open bed → Assign / reserve tenant.',
        'Or use Assign tenant in sidebar and pick resident + bed manually.',
        'Set move-in date, monthly rent, deposit for open-ended stays.',
      ],
      links: [{ label: 'Assign tenant', href: '/admin/bookings/new' }],
    },
    {
      id: 'move-bed',
      title: 'Move resident to another bed',
      category: 'Bed map',
      keywords: ['move', 'shift', 'transfer', 'bed change', 'room change'],
      summary: 'Relocate an active tenant without cancelling their booking.',
      steps: [
        'Bed map → click occupied bed → Move to another bed.',
        'Pick destination bed (must be available).',
        'Confirm — reservations update to the new bed.',
      ],
    },
    {
      id: 'activate-reservation',
      title: 'Activate a reserved booking (move-in today)',
      category: 'Bed map',
      keywords: ['activate', 'reservation', 'move in', 'pre-book', 'reserved'],
      summary: 'When a pre-booked tenant arrives, activate them on the bed map.',
      steps: [
        'Click bed showing Booked / reserved.',
        'Use Activate now in the side panel.',
        'Bed becomes occupied; billing continues on their booking.',
      ],
    },

    // ── Tenants ──
    {
      id: 'residents-list',
      title: 'Residents list & search',
      category: 'Residents',
      keywords: ['residents', 'search', 'list', 'tenant', 'active'],
      summary: 'All customers with active or past tenancies.',
      steps: [
        'Residents → search by name, phone, or email.',
        'Open profile for KYC status, active bed, rent, deposit.',
        'Bulk KYC WhatsApp — queue reminders for assigned residents with pending KYC.',
      ],
      links: [{ label: 'Residents', href: '/admin/residents' }],
    },
    {
      id: 'edit-tenancy',
      title: 'Edit rent, deposit, or bed on resident profile',
      category: 'Residents',
      keywords: ['edit rent', 'deposit', 'bed assignment', 'tenancy', 'correction'],
      summary: 'Fix assignment details without creating a new booking.',
      steps: [
        'Residents → open customer → Edit tenancy section.',
        'Update bed, monthly rent, or deposit fields as needed.',
        'Save — changes apply to future invoices; audit log records the edit.',
      ],
    },
    {
      id: 'assign-tenant-form',
      title: 'Assign tenant (admin-created booking)',
      category: 'Bookings',
      keywords: ['assign', 'new tenant', 'walk in', 'admin booking'],
      summary: 'Create open-ended monthly tenancy for walk-ins or phone bookings.',
      steps: [
        'Assign tenant → search existing resident or create via booking flow.',
        'Select PG bed, move-in date, rent, deposit.',
        'Submit — booking is confirmed; bed shows occupied/reserved based on date.',
      ],
      links: [{ label: 'Assign tenant', href: '/admin/bookings/new' }],
    },
    {
      id: 'booking-detail',
      title: 'Booking detail page',
      category: 'Bookings',
      keywords: ['booking', 'detail', 'cancel', 'extension', 'payments', 'checklist'],
      summary: 'Single booking hub: reservations, payments, invoices, extensions, ops checklist.',
      bullets: [
        'View bed reservations timeline and payment history.',
        'Rent & electricity invoice tables with links.',
        'Extensions — approve/deny for finite stays.',
        'Cancel booking — releases bed per policy.',
        'Operations checklist — dues cleared, deposit refund, bed housekeeping.',
        'Record offline payment when tenant pays cash/UPI outside the app.',
      ],
      links: [{ label: 'Bookings', href: '/admin/bookings' }],
    },

    // ── KYC ──
    {
      id: 'kyc-review',
      title: 'Review KYC submissions',
      category: 'KYC',
      keywords: ['kyc', 'aadhaar', 'approve', 'reject', 'identity', 'documents'],
      summary: 'Approve or reject ID uploads after booking payment.',
      steps: [
        'KYC review → pending queue.',
        'Open submission — view ID front/back and selfie.',
        'Approve if readable and matches resident, or Reject with reason.',
        'Resident re-uploads from Profile → Identity if rejected.',
        'WhatsApp nudge from list for pending assigned residents.',
      ],
      links: [{ label: 'KYC review', href: '/admin/residents/kyc' }],
    },

    // ── Collections ──
    {
      id: 'approve-payments',
      title: 'Approve payment proofs (Collections)',
      category: 'Collections',
      keywords: ['approve', 'payment', 'proof', 'screenshot', 'qr', 'pending', 'collections'],
      summary: 'Review UPI screenshots for bookings, rent, electricity, and extensions.',
      steps: [
        'Collections (all PGs) → pending queue.',
        'Open item — verify amount, UPI reference, payer name vs booking.',
        'Approve → marks invoice/booking paid and updates ledger.',
        'Reject → resident sees failure and can re-upload.',
      ],
      links: [{ label: 'Collections', href: '/admin/payments' }],
    },

    // ── Rent ──
    {
      id: 'rent-invoices',
      title: 'Rent invoices — generate & overdue',
      category: 'Rent billing',
      keywords: ['rent', 'invoice', 'generate', 'overdue', 'monthly', 'billing'],
      summary: 'Monthly rent invoices for all active open-ended tenants.',
      steps: [
        'Rent invoices → filter pending/overdue/paid.',
        'Generate invoices for a month (manual) or rely on cron if configured.',
        'Mark overdue sweep after due date passes.',
        'Residents pay via website; you approve proofs in Collections.',
      ],
      links: [{ label: 'Collections · billing tools', href: '/admin/collections' }],
    },

    // ── Electricity ──
    {
      id: 'electricity-meter',
      title: 'Record meter reading & generate bills',
      category: 'Electricity',
      keywords: ['electricity', 'meter', 'reading', 'units', 'bill', 'room'],
      summary: 'Primary workflow is per-PG Rooms page, not the global electricity list.',
      steps: [
        'PG → Rooms & electricity → room card → Electricity section.',
        'Upload meter photo and enter current reading.',
        'Generate bill — splits cost among active residents in that room.',
        'Residents pay from Resident area; approve in Collections.',
        'Global Electricity page shows all bills across PGs for overview.',
      ],
      links: [{ label: 'Electricity bills', href: '/admin/electricity' }],
    },

    // ── Deposits ──
    {
      id: 'deposit-ledger',
      title: 'Deposit ledger — adjust, deduct, refund',
      category: 'Deposits',
      keywords: ['deposit', 'ledger', 'refund', 'deduct', 'adjust', 'balance'],
      summary: 'Full audit trail per booking for collected, deducted, and refunded deposit.',
      steps: [
        'Deposits → pick booking, or open from booking/resident page.',
        'View ledger entries (collection at booking, vacating deduction, refund).',
        'Add manual deduct/adjust/refund with reason when needed.',
        'Refund only after rent, electricity, and penalties are cleared.',
      ],
      links: [{ label: 'Deposits', href: '/admin/deposits' }],
    },

    // ── Vacating ──
    {
      id: 'vacating-workflow',
      title: 'Vacating workflow (approve → complete)',
      category: 'Vacating',
      keywords: ['vacating', 'move out', 'notice', 'approve', 'complete', 'pre-book'],
      summary: `Residents need ${VACATING_NOTICE_MIN_DAYS}+ days notice to avoid 5-day rent penalty on deposit.`,
      steps: [
        'Vacating queue or bed map → pending request.',
        'Approve — bed becomes pre-bookable on website from vacating date.',
        'Complete — writes deposit deduction if any, cancels future invoices, frees bed.',
        'Reject / Cancel notice if resident changes plans.',
        'Undo approval only before completion if mistake.',
        'Admin can submit vacating on behalf of tenant from bed map.',
      ],
      links: [{ label: 'Vacating', href: '/admin/vacating' }],
    },

    // ── PS4 & email ──
    {
      id: 'ps4-admin',
      title: 'PS4 memberships',
      category: 'Add-ons',
      keywords: ['ps4', 'playstation', 'gaming', 'membership'],
      summary: 'View, activate, extend, or cancel gaming add-ons.',
      links: [{ label: 'PS4 memberships', href: '/admin/playstation' }],
    },
    {
      id: 'email-log',
      title: 'Email delivery log',
      category: 'Add-ons',
      keywords: ['email', 'log', 'sent', 'failed', 'rent reminder'],
      summary: 'Audit rent/electricity/vacating emails sent to residents.',
      links: [{ label: 'Email log', href: '/admin/emails' }],
    },

    // ── Troubleshooting ──
    {
      id: 'fix-payment-not-showing',
      title: 'Problem: Resident paid but booking/invoice still pending',
      category: 'Troubleshooting',
      keywords: ['payment not showing', 'pending', 'paid', 'proof', 'stuck', 'upi'],
      summary: 'Usually waiting for proof approval or wrong amount uploaded.',
      steps: [
        'Open Collections → filter pending for that PG/resident.',
        'If proof exists — verify amount matches invoice exactly, then Approve.',
        'If no proof — ask resident to upload screenshot from pay page.',
        'If wrong amount — reject proof; resident pays difference or admin records adjustment.',
        'Check booking detail → payments table for duplicate submissions.',
      ],
      links: [{ label: 'Collections', href: '/admin/payments' }],
    },
    {
      id: 'fix-bed-wrong-status',
      title: 'Problem: Bed shows wrong status on map or website',
      category: 'Troubleshooting',
      keywords: ['wrong status', 'bed', 'available', 'occupied', 'map', 'sync'],
      summary: 'Trace reservation, manual occupied flag, and vacating state.',
      steps: [
        'Bed map → click bed → read panel (occupied vs reserved vs open).',
        'If tenant moved in but shows Booked — use Activate now on reserved booking.',
        'If empty but shows Occupied — check manual occupied toggle; clear if set by mistake.',
        'If vacating approved — bed may show pre-bookable; complete vacating when they leave.',
        'Check booking detail for active reservation dates covering today.',
      ],
    },
    {
      id: 'fix-kyc-blocking',
      title: 'Problem: Resident cannot check in — KYC pending',
      category: 'Troubleshooting',
      keywords: ['kyc pending', 'check in', 'identity', 'blocked'],
      summary: 'Review and approve/reject KYC queue promptly.',
      steps: [
        'KYC review → find submission by name or booking.',
        'Approve clear documents or reject with reason for re-upload.',
        'Use bulk WhatsApp reminder on Residents list if many pending.',
      ],
      links: [{ label: 'KYC review', href: '/admin/residents/kyc' }],
    },
    {
      id: 'fix-overview-error',
      title: 'Problem: Overview page shows error banner',
      category: 'Troubleshooting',
      keywords: ['overview', 'error', 'dashboard', 'crash', 'database'],
      summary: 'Expand error detail — often DB connection or pending migration.',
      steps: [
        'Read Show error detail on the banner.',
        'If migration pending — run npm run db:migrate on server (Vercel deploy runs vercel-build).',
        'If connection refused — check DATABASE_URL in hosting env.',
        'If timeout — retry; overview runs many queries; check DB health.',
      ],
      links: [{ label: 'System / migrations', href: '/admin/system' }],
    },
    {
      id: 'fix-rent-not-generated',
      title: 'Problem: Rent invoice missing for a resident',
      category: 'Troubleshooting',
      keywords: ['rent missing', 'no invoice', 'generate', 'billing'],
      summary: 'Confirm active booking and generate invoices for the month.',
      steps: [
        'Resident profile → confirm active booking with open-ended stay.',
        'Rent invoices → Generate for target month.',
        'If booking cancelled or vacating completed — no new rent should generate.',
        'Check booking detail rent table for cancelled/overdue rows.',
      ],
    },
    {
      id: 'fix-electricity-split',
      title: 'Problem: Electricity bill amount looks wrong',
      category: 'Troubleshooting',
      keywords: ['electricity wrong', 'split', 'units', 'meter', 'reading'],
      summary: 'Verify meter readings and resident count in room for that period.',
      steps: [
        'PG Rooms → room electricity history — check previous vs current reading.',
        'Confirm number of active residents when bill was generated.',
        'Regenerate only if reading was entered wrong (contact dev if data locked).',
        'Prepaid/top-up entries may affect balance — check room electricity panel.',
      ],
    },
    {
      id: 'fix-deposit-refund',
      title: 'Problem: Deposit refund delayed or blocked',
      category: 'Troubleshooting',
      keywords: ['deposit refund', 'blocked', 'dues', 'vacating', 'pending'],
      summary: 'All dues must clear before refund; vacating must be completed.',
      steps: [
        'Booking detail ops checklist — rent/electricity overdue?',
        'Vacating → must be Completed, not just Approved.',
        'Deposits ledger — verify deduction for short notice if applicable.',
        'Record refund entry when UPI/bank transfer is sent.',
      ],
      links: [{ label: 'Deposits', href: '/admin/deposits' }],
    },
    {
      id: 'fix-customer-cannot-book',
      title: 'Problem: Customer cannot book a bed on website',
      category: 'Troubleshooting',
      keywords: ['cannot book', 'website', 'customer', 'available', 'blocked'],
      summary: 'Check bed status, manual occupied, gender policy, and holds.',
      steps: [
        'View same bed on customer site vs admin bed map.',
        'Bed maintenance/blocked/manual occupied prevents booking.',
        'Active hold from another pending_payment booking blocks until expiry (~15 min).',
        'Gender policy on PG must match customer selection if enforced.',
        'Notice/pre-book beds require future start date matching vacating date.',
      ],
    },
    {
      id: 'fix-extension',
      title: 'Problem: Stay extension failed or unpaid',
      category: 'Troubleshooting',
      keywords: ['extension', 'extend', 'failed', 'conflict', 'pay'],
      summary: 'Extensions only apply to finite stays; payment required to confirm.',
      steps: [
        'Booking detail → extensions section for status.',
        'Conflict — another reservation overlaps new end date; adjust dates or free bed.',
        'Pending payment — resident must pay on extension pay page; approve in Collections.',
        'Open-ended monthly stays do not use extensions — use rent invoices instead.',
      ],
    },
    {
      id: 'fix-assign-conflict',
      title: 'Problem: Cannot assign tenant — bed not available',
      category: 'Troubleshooting',
      keywords: ['assign failed', 'bed not available', 'conflict', 'reservation'],
      summary: 'Another reservation or hold may cover the dates.',
      steps: [
        'Bed map → check bed for hidden reservation or manual occupied.',
        'Bookings list → search bed for overlapping active/hold reservations.',
        'Release expired holds via cron or wait for hold expiry.',
        'Pick another bed or adjust move-in date.',
      ],
    },
    {
      id: 'daily-checklist',
      title: 'Daily manager checklist',
      category: 'Reference',
      keywords: ['daily', 'checklist', 'routine', 'manager', 'tasks'],
      summary: 'Suggested order for a typical operations day.',
      steps: [
        '1. Overview — scan collections and overdue counts.',
        '2. Collections — approve overnight payment proofs.',
        '3. KYC review — clear pending queue for move-ins today.',
        '4. Bed map — verify move-ins, activations, vacating completions.',
        '5. Rent invoices — check overdue; WhatsApp reminders if needed.',
        '6. Vacating — approve new notices; complete yesterday’s move-outs.',
        '7. Electricity — record meter readings on billing day.',
      ],
    },
  ],
};
