import {
  DEPOSIT_REFUND_BLOCKERS,
  DEPOSIT_REFUND_HEADLINE,
  DEPOSIT_REFUND_TIMING,
} from '@/src/lib/depositPolicy';
import type { GuideCatalog } from '@/src/lib/guides/types';

export const BOOKING_GUIDE: GuideCatalog = {
  id: 'booking',
  title: 'How to book a PG',
  subtitle:
    'Everything you need to find a bed, pay online, complete KYC, and move in — step by step.',
  articles: [
    {
      id: 'welcome',
      title: 'What is Awesome PG?',
      category: 'Getting started',
      keywords: ['awesome pg', 'what is', 'amenities', 'features', 'website'],
      summary: 'Premium paying-guest living with bed-first booking and transparent UPI payments.',
      paragraphs: [
        'Awesome PG lets you book an exact bed — not just a room — at premium properties. You browse live availability, pick your dates, pay securely by UPI, and manage everything from your online profile.',
        'Every property lists honest amenities: daily cleaning, free laundry, high-speed WiFi, gaming zones, chill rooms, and more. Prices, deposits, and bed status are shown upfront on the website.',
      ],
      links: [{ label: 'Browse PGs', href: '/pgs' }],
    },
    {
      id: 'browse-pgs',
      title: 'Browse properties and compare PGs',
      category: 'Finding a bed',
      keywords: ['browse', 'list', 'pg', 'property', 'compare', 'location'],
      summary: 'Start at Browse PGs to see all active properties, photos, and starting prices.',
      steps: [
        'Open Browse PGs from the top menu or footer.',
        'Tap a property card to open its detail page.',
        'Review photos, amenities, gender policy, and the interactive bed map.',
        'Use the date bar to see which beds are open for your move-in window.',
      ],
      links: [{ label: 'Browse PGs', href: '/pgs' }],
    },
    {
      id: 'bed-map-colors',
      title: 'Understanding the bed map (colors & labels)',
      category: 'Finding a bed',
      keywords: ['bed map', 'available', 'occupied', 'notice', 'maintenance', 'colors', 'status'],
      summary: 'Each bed shows a color and label so you know if you can book it today or pre-book later.',
      bullets: [
        'Available / Open — book this bed now for immediate or near-term move-in.',
        'Available soon / Pre-book — someone is leaving or the bed opens on a future date; you can reserve from that date.',
        'Notice period — a resident gave notice; the bed may become bookable after their leaving date.',
        'Occupied — someone is living here; not bookable unless a future date is shown.',
        'Booked — reserved for someone who has not moved in yet.',
        'Maintenance — temporarily unavailable.',
      ],
      tip: 'Tap any bed on the map to see details, pricing hints, and the Continue button when it is bookable.',
    },
    {
      id: 'choose-dates',
      title: 'Choose your stay dates and duration',
      category: 'Finding a bed',
      keywords: ['dates', 'daily', 'weekly', 'monthly', 'living here', 'open ended', 'duration'],
      summary: 'Pick move-in date and how long you want to stay — daily, weekly, monthly, or open-ended monthly living.',
      steps: [
        'On the PG page, set your move-in date (and checkout date for fixed stays).',
        'Choose duration mode: daily, weekly, monthly, or Living here (monthly open-ended).',
        'Living here is for long-term residents — rent is billed monthly after move-in.',
        'Fixed stays (daily/weekly/monthly with an end date) show a total upfront on the cart.',
      ],
      tip: 'Open-ended “Living here” stays renew monthly. You pay rent each month from your Resident area after move-in.',
    },
    {
      id: 'pick-room-bed',
      title: 'Pick a room and select your bed',
      category: 'Finding a bed',
      keywords: ['room', 'bed', 'select', 'sharing', 'ac', 'b1', 'b2'],
      summary: 'Open a room to see individual beds (B1, B2, …) and select one or more if booking for a group.',
      steps: [
        'From the PG bed map, tap a room or use Continue on an available bed.',
        'On the room page, green/available beds can be selected; grey occupied beds cannot.',
        'Review rent, deposit, and sharing count (e.g. 2-sharing, 3-sharing).',
        'Tap Continue to go to the booking cart.',
      ],
    },
    {
      id: 'sign-in',
      title: 'Create an account or sign in',
      category: 'Account',
      keywords: ['login', 'sign in', 'account', 'email', 'password', 'otp', 'register'],
      summary: 'You need a resident account to confirm a booking. Sign in with email and password.',
      steps: [
        'If prompted, go to Resident sign in.',
        'Existing users: enter email + password and sign in.',
        'New users: enter email, verify with a one-time code (OTP), add name and phone, then set a password.',
        'Forgot password? Use “Forgot password” — OTP verifies your email, then you set a new password.',
      ],
      tip: 'After first signup you may be asked to set a password before continuing to payment.',
      links: [{ label: 'Resident sign in', href: '/login?next=/pgs' }],
    },
    {
      id: 'booking-cart',
      title: 'Review your booking cart',
      category: 'Booking & payment',
      keywords: ['cart', 'confirm', 'quote', 'deposit', 'total', 'checkout'],
      summary: 'The cart shows bed lines, rent, security deposit, and total before you create the booking.',
      bullets: [
        'Subtotal — rent for your selected dates (fixed stays) or first period quote.',
        'Security deposit — collected with your first payment; refundable at checkout subject to policy.',
        'Optional PS4 gaming add-on — if offered at checkout, you can add a gaming membership plan.',
        'Pre-book vs book now — future move-in dates create a reservation; today/near-term dates book immediately after payment.',
      ],
      links: [{ label: 'Start a booking', href: '/pgs' }],
    },
    {
      id: 'pay-booking',
      title: 'Pay with UPI (QR + payment proof)',
      category: 'Booking & payment',
      keywords: ['pay', 'upi', 'qr', 'payment', 'screenshot', 'proof', 'deposit'],
      summary: 'Scan the PG UPI QR, pay the exact amount, then upload your payment screenshot.',
      steps: [
        'After creating the booking, open the Pay page for your booking code.',
        'Scan the UPI QR with PhonePe, Google Pay, Paytm, or your bank app.',
        'Pay the exact amount shown (deposit + rent/advance as quoted).',
        'Upload a clear screenshot of the successful payment.',
        'Submit — our team reviews and confirms usually within a short window.',
        'Watch the payment-success page or return to your booking for status updates.',
      ],
      tip: 'Pay the exact rupee amount shown. Wrong amounts delay confirmation.',
    },
    {
      id: 'after-payment',
      title: 'After payment — what happens next',
      category: 'Booking & payment',
      keywords: ['confirmed', 'pending', 'status', 'after payment', 'approval'],
      summary: 'Your booking moves to confirmed once payment is verified. Then complete KYC before move-in.',
      bullets: [
        'Pending payment — waiting for your UPI proof or admin approval.',
        'Confirmed — bed is reserved; complete KYC and prepare for move-in.',
        'You receive a booking code — save it and find the booking under My bookings or Profile.',
      ],
      links: [{ label: 'My bookings', href: '/account/bookings' }],
    },
    {
      id: 'kyc-checkin',
      title: 'Complete KYC (identity verification)',
      category: 'Move-in',
      keywords: ['kyc', 'identity', 'aadhaar', 'documents', 'check in', 'verification'],
      summary: 'Upload ID documents so we can verify you before check-in.',
      steps: [
        'Go to Profile → Identity tab (or follow the banner on your booking page).',
        'Upload clear photos: ID front, ID back, and a selfie.',
        'Submit — status shows Pending until admin approves.',
        'Once approved, you are ready for check-in on your move-in date.',
      ],
      tip: 'KYC is required for all residents. Rejected uploads can be resubmitted with clearer photos.',
      links: [{ label: 'Profile & KYC', href: '/account/profile?section=identity' }],
    },
    {
      id: 'pre-book-vs-now',
      title: 'Pre-book vs book now',
      category: 'Booking & payment',
      keywords: ['pre-book', 'reserve', 'future', 'move in', 'today'],
      summary: 'Future move-in dates reserve the bed; immediate dates activate after payment confirmation.',
      paragraphs: [
        'If your move-in date is in the future, you are pre-booking — the bed is held for you from that date.',
        'If the bed is open today and you move in soon, payment confirms your stay and the bed shows as booked/occupied on the map.',
        'Notice-period beds may allow pre-booking from the date the current resident leaves (once approved by the PG).',
      ],
    },
    {
      id: 'cancel-booking',
      title: 'Cancel a booking',
      category: 'Changes & support',
      keywords: ['cancel', 'refund', 'booking', 'withdraw'],
      summary: 'Cancel from your booking page if you have not moved in yet — refund rules depend on timing and policy.',
      steps: [
        'Open your booking via My bookings or the booking link.',
        'Use Cancel booking if the option is shown (typically before move-in / while pending).',
        'Refunds follow the cancellation policy shown on the page.',
      ],
      links: [{ label: 'My bookings', href: '/account/bookings' }],
    },
    {
      id: 'extend-stay',
      title: 'Extend a fixed stay',
      category: 'Changes & support',
      keywords: ['extend', 'extension', 'longer', 'checkout', 'stay'],
      summary: 'Fixed-date bookings can request an extension; open-ended monthly stays do not need extensions.',
      steps: [
        'Open your confirmed booking page.',
        'Tap Extend stay and pick a new checkout date.',
        'Pay the extension amount via UPI + proof on the extension payment page.',
        'Open-ended “Living here” tenants renew monthly — use the Resident guide for rent instead.',
      ],
      tip: 'Extensions are only for bookings with a fixed end date. Monthly living tenants pay rent invoices each month.',
    },
    {
      id: 'deposit-at-booking',
      title: 'Security deposit at booking',
      category: 'Booking & payment',
      keywords: ['deposit', 'security', 'refund', 'checkout'],
      summary: DEPOSIT_REFUND_HEADLINE,
      bullets: [
        DEPOSIT_REFUND_TIMING,
        DEPOSIT_REFUND_BLOCKERS,
        'Deposit balance and refund status appear in your Resident area after you move in.',
      ],
    },
    {
      id: 'help-support',
      title: 'Get help while booking',
      category: 'Changes & support',
      keywords: ['help', 'support', 'whatsapp', 'contact', 'roachie', 'problem'],
      summary: 'Use WhatsApp support or the in-app guide if you get stuck.',
      bullets: [
        'WhatsApp button — bottom-right on every page for quick questions.',
        'Roachie guide — interactive tips on browse, bed pick, and payment pages (when enabled).',
        'After move-in, switch to the Resident guide for rent, electricity, and vacating.',
      ],
      links: [
        { label: 'Resident guide', href: '/guide?type=resident' },
        { label: 'Browse PGs', href: '/pgs' },
      ],
    },
  ],
};
