import {
  DEPOSIT_REFUND_BLOCKERS,
  DEPOSIT_REFUND_HEADLINE,
  DEPOSIT_REFUND_TIMING,
} from '@/src/lib/depositPolicy';
import { VACATING_NOTICE_MIN_DAYS } from '@/src/services/billing';
import type { GuideCatalog } from '@/src/lib/guides/types';

export const RESIDENT_GUIDE: GuideCatalog = {
  id: 'resident',
  title: 'Resident guide',
  subtitle:
    'Pay rent and electricity, manage your profile & KYC, vacating, deposit refunds, and add-on services.',
  articles: [
    {
      id: 'sign-in',
      title: 'Sign in to your resident account',
      category: 'Account',
      keywords: ['login', 'sign in', 'email', 'password', 'forgot', 'otp'],
      summary: 'Use email + password daily. OTP is only for first signup or password reset.',
      steps: [
        'Go to Resident sign in from the header or footer.',
        'Enter your registered email and password.',
        'First time? Verify email with OTP, complete profile, then set a password.',
        'Forgot password? Request OTP → verify → set a new password.',
      ],
      links: [{ label: 'Sign in', href: '/login?next=/account/profile' }],
    },
    {
      id: 'profile-hub',
      title: 'Your profile hub (three tabs)',
      category: 'Account',
      keywords: ['profile', 'account', 'tabs', 'photo', 'phone', 'email'],
      summary: 'Profile, Identity (KYC), and Resident area — all under one account page.',
      bullets: [
        'Profile — name, phone, email, profile photo, change password.',
        'Identity — KYC document upload and verification status.',
        'Resident area — unlocks after your first confirmed booking: rent, electricity, deposit, vacating.',
      ],
      links: [{ label: 'Open profile', href: '/account/profile' }],
    },
    {
      id: 'change-password',
      title: 'Change your password',
      category: 'Account',
      keywords: ['password', 'change', 'security', 'reset'],
      summary: 'Update your password anytime from Profile or the change-password page.',
      steps: [
        'Sign in to your account.',
        'Open Profile → use Change password, or go to Account → Change password.',
        'Enter current password and your new password twice.',
        'Save — use the new password on your next sign-in.',
      ],
      links: [{ label: 'Change password', href: '/account/change-password' }],
    },
    {
      id: 'kyc-identity',
      title: 'KYC & identity verification',
      category: 'KYC',
      keywords: ['kyc', 'aadhaar', 'id', 'selfie', 'identity', 'documents', 'approved', 'rejected'],
      summary: 'Upload ID photos and a selfie. Admin reviews before check-in is fully cleared.',
      steps: [
        'Open Profile → Identity tab.',
        'Upload ID front, ID back, and a clear selfie (good lighting, readable text).',
        'Submit — status shows Pending review.',
        'Approved — you are verified. Rejected — read the reason, re-upload clearer photos.',
      ],
      tip: 'Complete KYC before move-in. Admin may WhatsApp you if documents are unclear.',
      links: [{ label: 'Identity / KYC', href: '/account/profile?section=identity' }],
    },
    {
      id: 'resident-area',
      title: 'Resident area overview',
      category: 'Living here',
      keywords: ['resident', 'dashboard', 'rent', 'electricity', 'deposit', 'vacating'],
      summary: 'Your home base for monthly life at the PG — billing, deposit, and move-out.',
      bullets: [
        'Rent invoices — monthly bills with pay links.',
        'Electricity — room meter bills split among residents.',
        'Deposit — balance, deductions, refund policy.',
        'Vacating — submit or track move-out notice.',
        'My services — PS4 gaming membership if subscribed.',
        'Payment history — per-booking ledger of all charges and payments.',
      ],
      links: [{ label: 'Resident area', href: '/account/profile?section=resident' }],
    },
    {
      id: 'pay-rent',
      title: 'Pay monthly rent',
      category: 'Payments',
      keywords: ['rent', 'invoice', 'monthly', 'pay', 'upi', 'qr', 'overdue', 'due'],
      summary: 'Each month you get a rent invoice — pay via UPI QR and upload proof.',
      steps: [
        'Open Resident area or the rent invoice link from email/WhatsApp.',
        'Tap Pay on the pending rent invoice.',
        'Scan the PG UPI QR and pay the exact invoice amount.',
        'Upload your payment screenshot and submit.',
        'Status updates to Paid once admin approves your proof (or auto-verified if enabled).',
      ],
      tip: 'Pay before the due date to avoid late fees. Overdue invoices show a penalty on the invoice.',
    },
    {
      id: 'pay-electricity',
      title: 'Pay electricity bills',
      category: 'Payments',
      keywords: ['electricity', 'meter', 'bill', 'units', 'room', 'split', 'pay'],
      summary: 'Room electricity is metered monthly and split among active residents in that room.',
      steps: [
        'When a bill is generated, you see it under Resident area → Electricity.',
        'Open the invoice — it shows units used, rate, and your share.',
        'Tap Pay, scan UPI QR, pay exact amount, upload screenshot.',
        'Meter photos and readings are recorded by the PG each month.',
      ],
      tip: 'If you moved mid-month, your share is calculated for the days you occupied the bed.',
    },
    {
      id: 'extra-deposit',
      title: 'Extra deposit or top-up (if asked)',
      category: 'Payments',
      keywords: ['extra deposit', 'top up', 'additional', 'deposit', 'dues'],
      summary: 'Sometimes admin requests an additional deposit or adjustment — pay through your booking or contact support.',
      paragraphs: [
        'Your deposit balance is tracked in the Resident area and deposit ledger.',
        'If management asks for an extra deposit (damage, policy, or adjustment), they will guide you via WhatsApp or email with the amount and reason.',
        'Pay using the UPI details shared by the PG and send proof to support, or ask admin to record an offline payment on your booking.',
      ],
      tip: 'Always get the amount and booking code in writing before paying an ad-hoc deposit.',
    },
    {
      id: 'deposit-refund',
      title: 'Deposit refund when you leave',
      category: 'Move-out',
      keywords: ['deposit', 'refund', 'checkout', 'leave', 'balance'],
      summary: DEPOSIT_REFUND_HEADLINE,
      bullets: [
        DEPOSIT_REFUND_TIMING,
        DEPOSIT_REFUND_BLOCKERS,
        'Vacating penalties (short notice) may be deducted from deposit — see Vacating section.',
        'Track refund status with admin after vacating is completed and dues are cleared.',
      ],
    },
    {
      id: 'vacating',
      title: 'Request vacating (move-out notice)',
      category: 'Move-out',
      keywords: ['vacating', 'move out', 'leave', 'notice', 'penalty', '14 days'],
      summary: `Give at least ${VACATING_NOTICE_MIN_DAYS} days notice to avoid a deposit deduction.`,
      steps: [
        'Open Resident area → Request vacating (or the vacating link for your booking).',
        'Pick your vacating (last) date.',
        `If notice is ${VACATING_NOTICE_MIN_DAYS}+ days: no rent penalty on deposit.`,
        `If notice is under ${VACATING_NOTICE_MIN_DAYS} days: a 5-day rent penalty may be deducted from deposit.`,
        'Submit — status shows Pending until admin approves.',
        'After approval, your bed may show as pre-bookable for new tenants from your leaving date.',
        'Cancel a pending request from Resident area if your plans change.',
      ],
      tip: 'Clear all rent and electricity dues before leaving to avoid blocking your deposit refund.',
    },
    {
      id: 'ps4-membership',
      title: 'PS4 / gaming membership',
      category: 'Services',
      keywords: ['ps4', 'playstation', 'gaming', 'membership', 'subscription', 'arcade'],
      summary: 'Optional gaming add-on — subscribe and pay monthly from Resident area.',
      steps: [
        'Subscribe from Resident area → My services, or add during initial booking if offered.',
        'Choose a plan (duration/pricing shown on screen).',
        'Pay via UPI + proof on the PS4 payment page.',
        'Renew or manage membership from My services while active.',
      ],
    },
    {
      id: 'payment-history',
      title: 'Payment history & receipts',
      category: 'Payments',
      keywords: ['history', 'receipt', 'ledger', 'past payments', 'proof'],
      summary: 'View all charges and download receipts for rent, electricity, and booking payments.',
      steps: [
        'Resident area → Payment history (or open history for a specific booking).',
        'Each row shows type, amount, date, and status.',
        'Tap a paid item to open a receipt where available.',
      ],
      links: [{ label: 'My bookings', href: '/account/bookings' }],
    },
    {
      id: 'my-bookings',
      title: 'My bookings list',
      category: 'Living here',
      keywords: ['bookings', 'booking code', 'status', 'confirmed'],
      summary: 'See all your bookings, open details, extend fixed stays, or jump to payment.',
      links: [{ label: 'My bookings', href: '/account/bookings' }],
    },
    {
      id: 'emails-notifications',
      title: 'Email notifications',
      category: 'Living here',
      keywords: ['email', 'notification', 'reminder', 'invoice', 'rent due'],
      summary: 'We email rent and electricity reminders to your registered address when bills are generated.',
      paragraphs: [
        'Keep your email up to date in Profile.',
        'Check spam if you miss an invoice — you can always pay from Resident area on the website.',
      ],
    },
    {
      id: 'common-issues',
      title: 'Common issues & what to do',
      category: 'Help',
      keywords: ['problem', 'stuck', 'payment not showing', 'kyc pending', 'help', 'support'],
      summary: 'Quick fixes for the most common resident questions.',
      bullets: [
        'Payment submitted but still pending — allow time for admin review; ensure screenshot shows amount, UPI ref, and date.',
        'KYC stuck on pending — wait for admin review (usually same day); re-upload if rejected.',
        'Cannot see Resident tab — you need at least one confirmed booking.',
        'Wrong amount paid — contact PG on WhatsApp with booking code and screenshot.',
        'Forgot password — use Forgot password on sign-in page (OTP reset).',
      ],
      links: [
        { label: 'Booking guide (new tenants)', href: '/guide?type=booking' },
        { label: 'WhatsApp support', href: '/pgs' },
      ],
    },
  ],
};
