/* eslint-disable no-console */
/**
 * Read-only production billing verification report.
 * Run: npx vercel env run --environment production npx tsx scripts/verify-billing-production-report.ts
 */
import { loadAppEnv } from '../src/lib/db/loadEnv';
loadAppEnv();

import { and, count, desc, eq, inArray, isNull, ne, sql, sum } from 'drizzle-orm';
import { db, closeDb } from '../src/db/client';
import {
  bedReservations,
  beds,
  billingGenerationFailures,
  billingGenerationRuns,
  bookings,
  customers,
  electricityBills,
  electricityInvoices,
  floors,
  notifications,
  pgs,
  rentInvoices,
  residentBillingProfiles,
  rooms,
} from '../src/db/schema';
import { nextBillingSchedulerRunUtc, todayInBillingTimezone } from '../src/lib/billing/billingTimezone';
import { collectibleResidentFilters } from '../src/lib/billing/productionDataFilter';
import {
  billingMonthForAnniversaryDate,
  effectiveBillingDayInMonth,
  firstAutoBillingDate,
  isBillingAnniversaryToday,
} from '../src/services/billing';
import { getDatabaseConnectionInfo } from '../src/lib/db/env';
import { getBillingRevenueMetrics } from '../src/services/billingRevenueMetrics';
import type { AdminSession } from '../src/lib/auth/session';
import { listPendingPaymentReviews } from '../src/services/paymentProofQueue';

type PassFail = 'PASS' | 'FAIL' | 'BLOCKED' | 'WARN';

const CRON: AdminSession = {
  kind: 'admin',
  sessionId: 'verify-billing',
  adminId: 'verify-billing',
  email: 'verify@system',
  fullName: 'Verify Billing',
  role: 'super_admin',
  pgScope: [],
  mustChangePassword: false,
  rememberMe: false,
  expiresAt: new Date(Date.now() + 86_400_000),
};

const report: Array<{ section: string; status: PassFail; detail: string }> = [];

function record(section: string, status: PassFail, detail: string) {
  report.push({ section, status, detail });
}

function fmtPaise(p: number) {
  return `₹${(p / 100).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;
}

async function listActiveMonthlyResidents() {
  return db
    .select({
      customerName: customers.fullName,
      pgName: pgs.name,
      roomNumber: rooms.roomNumber,
      bedCode: beds.bedCode,
      bookingId: bookings.id,
      bookingCode: bookings.bookingCode,
      durationMode: bookings.durationMode,
      checkIn: sql<string>`to_char(lower(${bedReservations.stayRange}), 'YYYY-MM-DD')`,
      billingDay: residentBillingProfiles.billingDay,
      billingAnchorDate: residentBillingProfiles.billingAnchorDate,
      firstAutoBillingDate: residentBillingProfiles.firstAutoBillingDate,
      autoGenerate: residentBillingProfiles.autoGenerate,
      lastAutoBillingMonth: residentBillingProfiles.lastAutoBillingMonth,
      lastAutoGeneratedAt: residentBillingProfiles.lastAutoGeneratedAt,
    })
    .from(bookings)
    .innerJoin(customers, eq(customers.id, bookings.customerId))
    .innerJoin(bedReservations, eq(bedReservations.bookingId, bookings.id))
    .innerJoin(beds, eq(beds.id, bedReservations.bedId))
    .innerJoin(rooms, eq(rooms.id, beds.roomId))
    .innerJoin(floors, eq(floors.id, rooms.floorId))
    .innerJoin(pgs, eq(pgs.id, floors.pgId))
    .leftJoin(residentBillingProfiles, eq(residentBillingProfiles.bookingId, bookings.id))
    .where(
      and(
        collectibleResidentFilters(),
        eq(bookings.status, 'confirmed'),
        eq(bedReservations.status, 'active'),
        eq(bedReservations.kind, 'primary'),
        sql`CURRENT_DATE <@ ${bedReservations.stayRange}`,
        inArray(bookings.durationMode, ['monthly', 'open_ended']),
      ),
    )
    .orderBy(pgs.name, rooms.roomNumber, beds.bedCode);
}


async function latestRentInvoice(bookingId: string) {
  const [row] = await db
    .select({
      id: rentInvoices.id,
      invoiceNumber: rentInvoices.invoiceNumber,
      billingMonth: rentInvoices.billingMonth,
      status: rentInvoices.status,
      dueDate: rentInvoices.dueDate,
      createdAt: rentInvoices.createdAt,
      paymentProofUrl: rentInvoices.paymentProofUrl,
    })
    .from(rentInvoices)
    .where(and(eq(rentInvoices.bookingId, bookingId), eq(rentInvoices.isAdhoc, false)))
    .orderBy(desc(rentInvoices.billingMonth))
    .limit(1);
  return row ?? null;
}

function nextInvoiceDate(billingDay: number, today: string, firstAuto: string | null): string {
  if (!firstAuto || today < firstAuto) return firstAuto ?? '—';
  const y = Number(today.slice(0, 4));
  const m = Number(today.slice(5, 7));
  const effectiveThisMonth = effectiveBillingDayInMonth(today, billingDay);
  const todayDay = Number(today.slice(8, 10));
  if (todayDay <= effectiveThisMonth) {
    return `${today.slice(0, 7)}-${String(effectiveThisMonth).padStart(2, '0')}`;
  }
  const nextM = m === 12 ? 1 : m + 1;
  const nextY = m === 12 ? y + 1 : y;
  const nextMonthIso = `${nextY}-${String(nextM).padStart(2, '0')}-01`;
  const eff = effectiveBillingDayInMonth(nextMonthIso, billingDay);
  return `${nextY}-${String(nextM).padStart(2, '0')}-${String(eff).padStart(2, '0')}`;
}

async function simulateSchedulerDryRun(today: string) {
  const billingMonth = billingMonthForAnniversaryDate(today);
  const rows = await db
    .select({
      bookingId: residentBillingProfiles.bookingId,
      customerId: residentBillingProfiles.customerId,
      customerName: customers.fullName,
      billingDay: residentBillingProfiles.billingDay,
      billingAnchorDate: residentBillingProfiles.billingAnchorDate,
      firstAutoBillingDate: residentBillingProfiles.firstAutoBillingDate,
      autoGenerate: residentBillingProfiles.autoGenerate,
      durationMode: bookings.durationMode,
    })
    .from(residentBillingProfiles)
    .innerJoin(bookings, eq(bookings.id, residentBillingProfiles.bookingId))
    .innerJoin(customers, eq(customers.id, residentBillingProfiles.customerId))
    .where(
      and(
        eq(residentBillingProfiles.autoGenerate, true),
        eq(bookings.status, 'confirmed'),
        collectibleResidentFilters(),
        inArray(bookings.durationMode, ['monthly', 'open_ended']),
      ),
    );

  const billedToday: string[] = [];
  const skipped: Array<{ name: string; reason: string }> = [];

  for (const row of rows) {
    const anchor = row.billingAnchorDate ?? row.firstAutoBillingDate;
    const firstAuto =
      row.firstAutoBillingDate ??
      (anchor ? firstAutoBillingDate(anchor, row.billingDay) : null);
    if (!firstAuto) {
      skipped.push({ name: row.customerName, reason: 'missing first_auto_billing_date' });
      continue;
    }
    if (!isBillingAnniversaryToday(today, row.billingDay, firstAuto)) {
      skipped.push({ name: row.customerName, reason: 'not billing anniversary today' });
      continue;
    }

    const [existing] = await db
      .select({ id: rentInvoices.id })
      .from(rentInvoices)
      .where(
        and(
          eq(rentInvoices.bookingId, row.bookingId),
          eq(rentInvoices.billingMonth, billingMonth),
          ne(rentInvoices.status, 'cancelled'),
        ),
      )
      .limit(1);

    if (existing) {
      skipped.push({ name: row.customerName, reason: `invoice already exists for ${billingMonth}` });
    } else {
      billedToday.push(row.customerName);
    }
  }

  return { billingMonth, billedToday, skipped };
}

async function main() {
  const conn = getDatabaseConnectionInfo();
  const today = todayInBillingTimezone();
  const nextRun = nextBillingSchedulerRunUtc().toISOString();

  console.log('═'.repeat(72));
  console.log('AWESOME PG — PRODUCTION BILLING VERIFICATION REPORT');
  console.log('═'.repeat(72));
  console.log(`Database host: ${conn.host}`);
  console.log(`Database name: ${conn.database}`);
  console.log(`Environment:   ${conn.environment}`);
  console.log(`Today (IST):   ${today}`);
  console.log(`Next scheduler run (UTC): ${nextRun}`);
  console.log('');

  if (conn.isLocalhost) {
    record('Production access', 'BLOCKED', 'Connected to localhost — not production Neon cluster');
    console.error('BLOCKED: Script must run against production via `vercel env run --environment production`');
    process.exit(2);
  }

  record('Production access', 'PASS', `Connected to ${conn.host}/${conn.database}`);

  // ── 1. Monthly / open-ended residents ─────────────────────────────────────
  console.log('\n## 1. Active monthly / Live Until Notice residents\n');
  const residents = await listActiveMonthlyResidents();
  const missingCycle: typeof residents = [];

  console.log(
    '| Resident | PG | Room | Bed | Check-in | Billing day | Next invoice | Last invoice | Status |',
  );
  console.log('|----------|-----|------|-----|----------|-------------|--------------|--------------|--------|');

  for (const r of residents) {
    const inv = await latestRentInvoice(r.bookingId);
    const firstAuto =
      r.firstAutoBillingDate ??
      (r.billingAnchorDate
        ? firstAutoBillingDate(r.billingAnchorDate, r.billingDay ?? 5)
        : r.checkIn
          ? firstAutoBillingDate(r.checkIn, r.billingDay ?? 5)
          : null);
    const nextInv = nextInvoiceDate(r.billingDay ?? 5, today, firstAuto);
    const status = inv?.status ?? 'none';
    const lastInv = inv ? `${inv.invoiceNumber} (${inv.billingMonth.slice(0, 7)})` : '—';

    if (!r.billingAnchorDate || !r.firstAutoBillingDate || r.autoGenerate === null) {
      missingCycle.push(r);
    }

    console.log(
      `| ${r.customerName} | ${r.pgName} | ${r.roomNumber} | ${r.bedCode} | ${r.checkIn} | ${r.billingDay ?? '?'} | ${nextInv} | ${lastInv} | ${status} |`,
    );
  }

  if (missingCycle.length === 0) {
    record('Monthly residents billing cycle', 'PASS', `${residents.length} active monthly/open_ended — all have cycle fields`);
  } else {
    record(
      'Monthly residents billing cycle',
      'FAIL',
      `${missingCycle.length} missing billing profile cycle: ${missingCycle.map((r) => r.customerName).join(', ')}`,
    );
  }

  // ── 2. Fixed-date residents ───────────────────────────────────────────────
  console.log('\n## 2. Fixed-date bookings (must be excluded from auto billing)\n');
  const fixedRows = await db
    .select({
      customerName: customers.fullName,
      bookingCode: bookings.bookingCode,
      durationMode: bookings.durationMode,
      autoGenerate: residentBillingProfiles.autoGenerate,
      monthlyInvoices: sql<number>`(
        SELECT count(*)::int FROM rent_invoices ri
        WHERE ri.booking_id = ${bookings.id}
          AND ri.is_adhoc = false
          AND ri.status != 'cancelled'
      )`,
    })
    .from(bookings)
    .innerJoin(customers, eq(customers.id, bookings.customerId))
    .leftJoin(residentBillingProfiles, eq(residentBillingProfiles.bookingId, bookings.id))
    .where(
      and(
        collectibleResidentFilters(),
        eq(bookings.status, 'confirmed'),
        eq(bookings.durationMode, 'fixed_stay'),
        sql`EXISTS (
          SELECT 1 FROM bed_reservations br
          WHERE br.booking_id = ${bookings.id}
            AND br.status = 'active'
            AND CURRENT_DATE <@ br.stay_range
        )`,
      ),
    );

  let fixedFail = false;
  for (const f of fixedRows) {
    const auto = f.autoGenerate !== false;
    const bad = auto || (f.monthlyInvoices ?? 0) > 0;
    if (bad) fixedFail = true;
    console.log(
      `- ${f.customerName} (${f.bookingCode}): auto_generate=${f.autoGenerate ?? 'null'}, monthly_invoices=${f.monthlyInvoices}${bad ? ' ⚠' : ''}`,
    );
  }

  record(
    'Fixed-date exclusion',
    fixedFail ? 'FAIL' : fixedRows.length === 0 ? 'PASS' : 'PASS',
    fixedFail
      ? 'Some fixed_stay bookings have auto_generate=true or monthly invoices'
      : `${fixedRows.length} active fixed_stay — all excluded from auto billing`,
  );

  // ── 3. Scheduler dry-run ──────────────────────────────────────────────────
  console.log('\n## 3. Scheduler simulation (read-only, no writes)\n');
  const sim = await simulateSchedulerDryRun(today);
  console.log(`Billing month target: ${sim.billingMonth}`);
  console.log(`Would bill today (${sim.billedToday.length}): ${sim.billedToday.join(', ') || '—'}`);
  console.log(`Skipped (${sim.skipped.length}):`);
  for (const s of sim.skipped.slice(0, 15)) {
    console.log(`  - ${s.name}: ${s.reason}`);
  }
  if (sim.skipped.length > 15) console.log(`  … and ${sim.skipped.length - 15} more`);

  const [lastRun] = await db
    .select()
    .from(billingGenerationRuns)
    .orderBy(desc(billingGenerationRuns.startedAt))
    .limit(1);

  const [failCount] = await db
    .select({ count: count() })
    .from(billingGenerationFailures)
    .where(isNull(billingGenerationFailures.resolvedAt));

  const dupCheck = await db.execute<{ booking_id: string; billing_month: string; c: number }>(sql`
    SELECT booking_id, billing_month, count(*)::int AS c
    FROM rent_invoices
    WHERE is_adhoc = false AND status != 'cancelled'
    GROUP BY booking_id, billing_month
    HAVING count(*) > 1
    LIMIT 10
  `);

  record(
    'Scheduler dry-run',
    dupCheck.length > 0 ? 'FAIL' : 'PASS',
    dupCheck.length > 0
      ? `${dupCheck.length} duplicate (booking, month) invoice groups found`
      : `Last run: ${lastRun?.status ?? 'none'} · created ${lastRun?.createdCount ?? 0} · failed ${lastRun?.failedCount ?? 0} · unresolved failures ${failCount?.count ?? 0}`,
  );

  // ── 4. Resident flow sample ───────────────────────────────────────────────
  console.log('\n## 4. Resident payment flow (sample monthly resident)\n');
  const [flowSample] = await db
    .select({
      customerName: customers.fullName,
      bookingId: bookings.id,
      invoiceId: rentInvoices.id,
      invoiceNumber: rentInvoices.invoiceNumber,
      status: rentInvoices.status,
      paymentProofUrl: rentInvoices.paymentProofUrl,
      billingMonth: rentInvoices.billingMonth,
      paidAt: rentInvoices.paidAt,
    })
    .from(rentInvoices)
    .innerJoin(bookings, eq(bookings.id, rentInvoices.bookingId))
    .innerJoin(customers, eq(customers.id, rentInvoices.customerId))
    .where(
      and(
        collectibleResidentFilters(),
        eq(rentInvoices.isAdhoc, false),
        inArray(bookings.durationMode, ['monthly', 'open_ended']),
      ),
    )
    .orderBy(desc(rentInvoices.updatedAt))
    .limit(1);

  if (flowSample) {
    const transitions = [
      `Invoice ${flowSample.invoiceNumber} (${flowSample.billingMonth.slice(0, 7)})`,
      `Status: ${flowSample.status}`,
      flowSample.paymentProofUrl ? 'Proof uploaded: yes' : 'Proof uploaded: no',
      flowSample.paidAt ? `Paid at: ${flowSample.paidAt.toISOString()}` : 'Paid at: —',
    ];
    transitions.forEach((t) => console.log(`  · ${t}`));
    record('Resident flow sample', 'PASS', `Latest invoice for ${flowSample.customerName}: ${flowSample.status}`);
  } else {
    record('Resident flow sample', 'WARN', 'No monthly rent invoices found to trace');
  }

  // ── 5. Electricity ────────────────────────────────────────────────────────
  console.log('\n## 5. Electricity (latest batch)\n');
  const [elecBatch] = await db
    .select({
      id: electricityBills.id,
      pgName: pgs.name,
      roomNumber: rooms.roomNumber,
      billingMonth: electricityBills.billingMonth,
      totalPaise: electricityBills.totalPaise,
      monthlyOccupantCount: electricityBills.monthlyOccupantCount,
      createdAt: electricityBills.createdAt,
    })
    .from(electricityBills)
    .innerJoin(rooms, eq(rooms.id, electricityBills.roomId))
    .innerJoin(floors, eq(floors.id, rooms.floorId))
    .innerJoin(pgs, eq(pgs.id, floors.pgId))
    .orderBy(desc(electricityBills.createdAt))
    .limit(1);

  if (elecBatch) {
    const elecInvoices = await db
      .select({
        customerName: customers.fullName,
        amountPaise: electricityInvoices.amountPaise,
        status: electricityInvoices.status,
        paymentProofUrl: electricityInvoices.paymentProofUrl,
      })
      .from(electricityInvoices)
      .innerJoin(customers, eq(customers.id, electricityInvoices.customerId))
      .where(eq(electricityInvoices.electricityBillId, elecBatch.id));

    console.log(
      `Latest batch: ${elecBatch.pgName} room ${elecBatch.roomNumber} · ${elecBatch.billingMonth.slice(0, 7)} · ${fmtPaise(elecBatch.totalPaise)} · ${elecBatch.monthlyOccupantCount} occupants`,
    );
    for (const ei of elecInvoices) {
      console.log(
        `  - ${ei.customerName}: ${fmtPaise(ei.amountPaise)} · ${ei.status}${ei.paymentProofUrl ? ' · proof uploaded' : ''}`,
      );
    }
    const splitTotal = elecInvoices.reduce((a, r) => a + r.amountPaise, 0);
    const splitOk = Math.abs(splitTotal - elecBatch.totalPaise) < 100;
    record(
      'Electricity split',
      splitOk ? 'PASS' : 'WARN',
      splitOk
        ? `Split sums to ${fmtPaise(splitTotal)} vs bill ${fmtPaise(elecBatch.totalPaise)}`
        : `Split total ${fmtPaise(splitTotal)} vs bill ${fmtPaise(elecBatch.totalPaise)}`,
    );
  } else {
    record('Electricity', 'WARN', 'No electricity bills in production');
  }

  // ── 6. Billing Center counts ──────────────────────────────────────────────
  console.log('\n## 6. Billing Center DB counts\n');
  const billingMonth = `${today.slice(0, 7)}-01`;

  const [generatedToday] = await db
    .select({ count: count() })
    .from(rentInvoices)
    .where(
      and(
        eq(rentInvoices.isAdhoc, false),
        sql`(${rentInvoices.createdAt} AT TIME ZONE 'Asia/Kolkata')::date = ${today}::date`,
      ),
    );

  const [pendingRent] = await db
    .select({ count: count(), total: sum(rentInvoices.rentPaise) })
    .from(rentInvoices)
    .innerJoin(bookings, eq(bookings.id, rentInvoices.bookingId))
    .innerJoin(customers, eq(customers.id, rentInvoices.customerId))
    .where(
      and(
        collectibleResidentFilters(),
        eq(rentInvoices.isAdhoc, false),
        inArray(rentInvoices.status, ['pending', 'overdue', 'payment_in_progress']),
      ),
    );

  const [paidRentMtd] = await db
    .select({ count: count() })
    .from(rentInvoices)
    .where(
      and(
        eq(rentInvoices.isAdhoc, false),
        eq(rentInvoices.status, 'paid'),
        sql`date_trunc('month', ${rentInvoices.paidAt}) = date_trunc('month', ${billingMonth}::date)`,
      ),
    );

  const pendingApprovals = await listPendingPaymentReviews(CRON);

  console.log(`Generated today: ${generatedToday?.count ?? 0}`);
  console.log(`Pending rent invoices: ${pendingRent?.count ?? 0} (${fmtPaise(Number(pendingRent?.total ?? 0))})`);
  console.log(`Paid rent MTD: ${paidRentMtd?.count ?? 0}`);
  console.log(`Pending payment approvals: ${pendingApprovals.length}`);
  console.log(`Unresolved generation failures: ${failCount?.count ?? 0}`);

  record('Billing Center counts', 'PASS', 'Counts computed from production DB');

  // ── 7. Revenue reconciliation ─────────────────────────────────────────────
  console.log('\n## 7. Revenue reconciliation (current month)\n');
  const metrics = await getBillingRevenueMetrics(
    billingMonth,
    {
      rentPaise: Number(
        (
          await db
            .select({ t: sum(rentInvoices.paidPrincipalPaise) })
            .from(rentInvoices)
            .where(
              and(
                eq(rentInvoices.status, 'paid'),
                sql`date_trunc('month', ${rentInvoices.paidAt}) = date_trunc('month', ${billingMonth}::date)`,
                collectibleResidentFilters(),
              ),
            )
        )[0]?.t ?? 0,
      ),
      electricityPaise: Number(
        (
          await db
            .select({ t: sum(electricityInvoices.paidPaise) })
            .from(electricityInvoices)
            .where(
              and(
                eq(electricityInvoices.status, 'paid'),
                sql`date_trunc('month', ${electricityInvoices.paidAt}) = date_trunc('month', ${billingMonth}::date)`,
                collectibleResidentFilters(),
              ),
            )
        )[0]?.t ?? 0,
      ),
    },
    {
      rentPaise: Number(pendingRent?.total ?? 0),
      electricityPaise: Number(
        (
          await db
            .select({ t: sum(electricityInvoices.amountPaise) })
            .from(electricityInvoices)
            .innerJoin(bookings, eq(bookings.id, electricityInvoices.bookingId))
            .innerJoin(customers, eq(customers.id, electricityInvoices.customerId))
            .where(
              and(
                collectibleResidentFilters(),
                eq(electricityInvoices.status, 'pending'),
              ),
            )
        )[0]?.t ?? 0,
      ),
    },
  );

  console.log(`Rent  — Generated: ${fmtPaise(metrics.rent.generatedPaise)} | Collected MTD: ${fmtPaise(metrics.rent.collectedPaise)} | Pending: ${fmtPaise(metrics.rent.pendingPaise)} | Overdue: ${fmtPaise(metrics.rent.overduePaise)}`);
  console.log(
    `Elec  — Generated: ${fmtPaise(metrics.electricity.generatedPaise)} | Collected MTD: ${fmtPaise(metrics.electricity.collectedPaise)} | Pending: ${fmtPaise(metrics.electricity.pendingPaise)} | Overdue: ${fmtPaise(metrics.electricity.overduePaise)}`,
  );

  const rentBalanced =
    metrics.rent.generatedPaise >= metrics.rent.collectedPaise + metrics.rent.pendingPaise - metrics.rent.overduePaise;
  record(
    'Revenue rent',
    rentBalanced ? 'PASS' : 'WARN',
    `Generated ≥ collected + pending (approx): ${rentBalanced}`,
  );
  record('Revenue electricity', 'PASS', 'Metrics computed');

  // ── 8. Notifications ──────────────────────────────────────────────────────
  console.log('\n## 8. Admin notifications (rent batch)\n');
  const batchNotifs = await db
    .select({
      type: notifications.type,
      title: notifications.title,
      createdAt: notifications.createdAt,
    })
    .from(notifications)
    .where(inArray(notifications.type, ['rent_batch_generated', 'rent_batch_failed']))
    .orderBy(desc(notifications.createdAt))
    .limit(5);

  for (const n of batchNotifs) {
    console.log(`  - [${n.type}] ${n.title} · ${n.createdAt.toISOString()}`);
  }
  record(
    'Batch notifications',
    batchNotifs.length > 0 ? 'PASS' : 'WARN',
    batchNotifs.length > 0 ? `${batchNotifs.length} recent rent batch notifications` : 'No rent_batch_* notifications yet (scheduler may not have run)',
  );

  // ── Summary ───────────────────────────────────────────────────────────────
  console.log('\n' + '═'.repeat(72));
  console.log('SUMMARY');
  console.log('═'.repeat(72));
  for (const r of report) {
    console.log(`[${r.status}] ${r.section}`);
    console.log(`       ${r.detail}`);
  }

  const fails = report.filter((r) => r.status === 'FAIL' || r.status === 'BLOCKED').length;
  const safe = fails === 0;
  console.log('\n' + (safe ? '✓ PRODUCTION READY (verification passed)' : '✗ NOT PRODUCTION READY — see FAIL/BLOCKED items'));
  await closeDb();
  process.exit(fails > 0 ? 1 : 0);
}

main().catch(async (err) => {
  console.error(err);
  await closeDb().catch(() => undefined);
  process.exit(1);
});
